#ifndef FILTERINTERFACES_GLOBAL_H
#define FILTERINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCIVI_LIBRARY)
#define SCIVI_LIBRARY_EXPORT
#else
#define SCIVI_LIBRARY_EXPORT
#endif

#endif  // FILTERINTERFACES_GLOBAL_H
